language: node_js
node_js:
  - "4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "olNurvzwF8xVfzLeeCaN/PUNGNoUozxHFq8XI4ypOiKzsJTUzX85sLDcnI6qqNOtUCSUbqV+kxmnme0GlEz8I5kpMkMVOBhByjXEFKJ04tC8qhGQlidD8j63pFkCelYraf2raGZn/rr1OMaZOBcTzibOq0E21ABgGxRgrVtKQTcTHCxzcaoZSZfVGGfkz+airEtRXHDGFmBIQc1Fo5XNa+Yh20AEnfc60PAaOPJgXRS+hl0ObMbyLdL55ogFp6QtZw4DYIfcUB841rqhisWwaOB+xSq4zLgPkNI2NBG5kl/lUuGsMcZqcP75o6Gr+T262UKI07NHtzZVddV3YMBOkBvBCs3iLUpKe4EsdC4teFtX3t+I4KaLqY7ajuy152lew9KUYYIt4zG8GhsWJCZ49p/UGXFwaEbb6jRKS7Um5cGjbajxwQJpSx2CxQc0tbU6Y2cX6cXmd2RztQ+psDloAXuGVZmcBFAitslhV2m8b5hr36OgI+7ozmW9MIwni5vrDGf7ZsPAxEcdr4tIMUlrj8zdEO5DX+E5nZPGXopo1vV7ZZ/wLu6KRETtHJLVs10azMMqO8y9l74ICb9WhC9KEJ73mKEPUXHLf8E132W1JwZGQSgJsoUWzMKc8qiwGEHkG++3oIR/PG7ZmfdACwOwDuzRKtTNx2VMIPk+kYBoCI0=" # GH_TOKEN

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
